name = "winturbate"
compatibility_date = "2025-06-15"
workers_dev = true
main = "index.js"

[build]
command = "npm run build"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
