name = "winturbate"
compatibility_date = "2025-06-15"
workers_dev = true

[build]
command = "npm run build"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"
